server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jzh8686/project-configuration
          search-paths: /**
          repos:
            patterns: material
  application:
    name: config-server



